apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-mysql
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: library-mysql
  template:
    metadata:
      labels:
        name: library-mysql
        version: "8"
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - name: jdbc
          containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_ROOT_PASSWORD
          value: pass
---
apiVersion: v1
kind: Service
metadata:
  name: library-mysql
  namespace: test
  labels:
    name: library-mysql
spec:
  ports:
    - port: 3306
      targetPort: jdbc
      protocol: TCP
      name: jdbc
  selector:
    name: library-mysql
    version: "8"
  type: ClusterIP