name: Workflow 2 - Run all tests when push develop branch

on: 
  push:
    branches: 
    - develop
    paths:
    - 'src/**'
    - 'pom.xml'

jobs:
  test-all:
    name: Build Java project, run all tests and push Docker image to DockerHub and GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code on the runner
      uses: actions/checkout@v3

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-    

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run unitary test
      run: mvn -B -Dtest=*UnitaryTest test

    - name: Run REST test
      run: mvn -B -Dtest=*RestTest test
      
    - name: Run e2e test
      run: mvn -B -Dtest=*SeleniumTest test

    - name: Generate tag
      run: echo "tag=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)" >> $GITHUB_OUTPUT
      id: project

    - name: Generate Docker image
      run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=books-reviewer
    
    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag an push Docker image to DockerHub
      run: | 
          IMAGE_VERSION=${{ steps.project.outputs.tag }}
          docker tag books-reviewer ${{ secrets.DOCKERHUB_USERNAME }}/books-reviewer:$IMAGE_VERSION-dev
          docker tag books-reviewer ${{ secrets.DOCKERHUB_USERNAME }}/books-reviewer:dev
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/books-reviewer:$IMAGE_VERSION-dev
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/books-reviewer:dev
    
    - name: Login to GitHub Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Tag and push Docker image to GitHub Container Registry
      run: |
          IMAGE_VERSION=${{ steps.project.outputs.tag }}
          IMAGE_USER=$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')
          docker tag books-reviewer ghcr.io/$IMAGE_USER/books-reviewer:$IMAGE_VERSION-dev
          docker tag books-reviewer ghcr.io/$IMAGE_USER/books-reviewer:dev
          docker push ghcr.io/$IMAGE_USER/books-reviewer:$IMAGE_VERSION-dev
          docker push ghcr.io/$IMAGE_USER/books-reviewer:dev
