name: Workflow 4 - All unit tests and rest tests on commit into release branch

on: 
    push:
        branches: 
            - release/*
        paths:
            - 'src/**'
            - 'pom.xml'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code on the runner
              uses: actions/checkout@v3

            - name: Cache Maven dependencies
              uses: actions/cache@v3
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: ${{ runner.os }}-maven-    

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: Build with Maven
              run: mvn clean install -DskipTests

            - name: Setup tests scripts
              run: chmod +x ./scripts/*.sh

            - name: Unit tests
              run: ./scripts/run-unit-tests.sh

            - name: API rest tests
              run: ./scripts/run-rest-tests.sh